export const cardTranslate = (text: string) => {
  const keyName = 'card'
  if (text === `${keyName}:yukari`) return '유카리'
  if (text === `${keyName}:yuuka`) return '유우카'
  if (text === `${keyName}:ibuki`) return '이부키'
  if (text === `${keyName}:hiyori`) return '히요리'
  if (text === `${keyName}:alice`) return '엘리스'
  if (text === `${keyName}:hinata`) return '히나타'
  if (text === `${keyName}:hanako-swimsuit`) return '수영복 하나코'
  if (text === `${keyName}:chise-swimsuit`) return '수영복 치세'
  if (text === `${keyName}:eimi-swimsuit`) return '수영복 에이미'
  if (text === `${keyName}:azusa-swimsuit`) return '수영복 아즈사'
  if (text === `${keyName}:chinatsu`) return '치나츠'
  if (text === `${keyName}:atsuko`) return '아츠코'
  if (text === `${keyName}:ako`) return '아코'
  if (text === `${keyName}:akane`) return '아카네'
  if (text === `${keyName}:asuna`) return '아스나'
  if (text === `${keyName}:chihiro`) return '치히로'
  if (text === `${keyName}:airi`) return '에이리'
  if (text === `${keyName}:noa`) return '노아'
  if (text === `${keyName}:minori`) return '미노리'
  if (text === `${keyName}:saten-ruiko`) return '사텐 루이코'
  if (text === `${keyName}:renge`) return '렌게'
  if (text === `${keyName}:tsubaki`) return '츠바키'
  if (text === `${keyName}:mutsuki`) return '무츠키'
  if (text === `${keyName}:miyako`) return '미야코'
  if (text === `${keyName}:miyako-swimsuit`) return '수영복 미야코'
  if (text === `${keyName}:sakurako`) return '사쿠라코'
  if (text === `${keyName}:haruna`) return '하루나'
  if (text === `${keyName}:kirino`) return '키리노'
  if (text === `${keyName}:izumi`) return '이즈미'
  if (text === `${keyName}:sena`) return '세나'
  if (text === `${keyName}:neru`) return '네루'
  if (text === `${keyName}:koyuki`) return '코유키'
  if (text === `${keyName}:kikyou`) return '키쿄우'
  if (text === `${keyName}:tsukuyo`) return '츠쿠요'
  if (text === `${keyName}:saori`) return '사오리'
  if (text === `${keyName}:shimiko`) return '시미코'
  if (text === `${keyName}:marina`) return '마리나'
  if (text === `${keyName}:mari`) return '마리'
  if (text === `${keyName}:aru`) return '아루'
  if (text === `${keyName}:wakamo`) return '와카모'
  if (text === `${keyName}:shokuhou-misaki`) return '쇼쿠호 미사키'
  if (text === `${keyName}:shiroko`) return '시로코'
  if (text === `${keyName}:hoshino`) return '호시노'
  if (text === `${keyName}:mashiro`) return '마시로'
  if (text === `${keyName}:misaka-mikoto`) return '미사카 미코토'
  if (text === `${keyName}:miku`) return '미쿠'
  if (text === `${keyName}:kaho`) return '카호'
  if (text === `${keyName}:kayoko`) return '카요코'
  if (text === `${keyName}:megu`) return '메구'
  if (text === `${keyName}:kaede`) return '카에데'
  if (text === `${keyName}:iroha`) return '이로하'
  if (text === `${keyName}:kotama`) return '코타마'
  if (text === `${keyName}:saki`) return '사키'
  if (text === `${keyName}:yuzu`) return '유즈'
  if (text === `${keyName}:chise`) return '치세'
  if (text === `${keyName}:hare`) return '하레'
  if (text === `${keyName}:haruka`) return '하루카'
  if (text === `${keyName}:tsurugi`) return '츠루기'
  if (text === `${keyName}:serina`) return '세리나'
  if (text === `${keyName}:serika`) return '세리카'
  if (text === `${keyName}:nodoka`) return '노도카'
  if (text === `${keyName}:tomoe`) return '토모에'
  if (text === `${keyName}:kotori`) return '코토리'
  if (text === `${keyName}:yoshimi`) return '요시미'
  if (text === `${keyName}:akari`) return '아카리'
  if (text === `${keyName}:fubuki`) return '후부키'
  if (text === `${keyName}:ayane`) return '아야네'
  if (text === `${keyName}:fuuka`) return '후우카'
  if (text === `${keyName}:hanae`) return '하나에'
  if (text === `${keyName}:himari`) return '히마리'
  if (text === `${keyName}:hina`) return '히나'
  if (text === `${keyName}:suzumi`) return '스즈미'
  if (text === `${keyName}:toki`) return '토키'
  if (text === `${keyName}:junko`) return '준코'
  if (text === `${keyName}:maki`) return '마키'
  if (text === `${keyName}:kazusa`) return '카즈사'
  if (text === `${keyName}:karin`) return '카린'
  if (text === `${keyName}:nonomi`) return '노노미'

  return text
}
